### ISSUE TITLE
b64decode TypeError: Incorrect padding

### ISSUE THREAD

**Issue by sln-1550** [ChrisTheCoolHut/Zeratool#13]
I use the sample script, but failed. The output is following:
(zeratool) test@ubuntu:~/tools/Zeratool$ python zeratool.py challenges/ret -u ctf.hackucf.org -p 9003
[+] Checking pwn type...
[+] Checking for overflow pwn type...
[+] Vulnerable path found '0000000000000000000000000p00000000000000000000000000000000000000\xef\xbe\xad\xde000000000000AAAA000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
[+] Triggerable with STDIN : '0000000000000000000000000p00000000000000000000000000000000000000\xef\xbe\xad\xde000000000000AAAA000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
[+] Getting binary protections
Traceback (most recent call last):
  File "zeratool.py", line 80, in <module>
    main()
  File "zeratool.py", line 61, in main
    properties['win_functions'] = winFunctionDetector.getWinFunctions(args.file)
  File "/home/test/tools/Zeratool/lib/winFunctionDetector.py", line 34, in getWinFunctions
    decoded_value = base64.b64decode(value)
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

Any way, my ubuntu is 16.04.

**Comment by d1ves** [comment]
$ python zeratool.py challenges/easy_format
[+] Checking pwn type...
[+] Checking for overflow pwn type...
[+] Checking for format string pwn type...
[+] Found symbolic buffer at position 0 of length 49
[+] Found symbolic buffer at position 0 of length 49
[+] Found symbolic buffer at position 0 of length 49
[+] Found symbolic buffer at position 0 of length 49
[+] Found symbolic buffer at position 0 of length 49
[+] Getting binary protections
Traceback (most recent call last):
  File "zeratool.py", line 80, in <module>
    main()
  File "zeratool.py", line 61, in main
    properties['win_functions'] = winFunctionDetector.getWinFunctions(args.file)
  File "/home/kali/Documents/Zeratool/lib/winFunctionDetector.py", line 38, in getWinFunctions
    decoded_value = base64.b64decode(value)
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by ChrisTheCoolHut** [comment]
157d9fd

It looks like radare2 no longer base64 encodes all it's strings. So I removed the base64 decode
