### ISSUE TITLE
formatDetector.py-Error

### ISSUE THREAD

**Issue by DeeLMind** [ChrisTheCoolHut/Zeratool#4]
> handle_connect = p.loader.main_object.get_symbol('handle_connection')

> state = p.factory.entry_state(addr=handle_connect.rebased_addr)

- Error : handle_connect !=   handle_connection

**Comment by ChrisTheCoolHut** [comment]
Thank you for reporting.

Fixed in commit [7097ff2816b8019bf2d9a1944847f007c0607c62](https://github.com/ChrisTheCoolHut/Zeratool/commit/7097ff2816b8019bf2d9a1944847f007c0607c62)
