### ISSUE TITLE
Angr 8 and python3 pwntools support

### ISSUE THREAD

**Issue by Pl0414141** [ChrisTheCoolHut/Zeratool#9]
Hi,

it would be nice to support version 8.x of Angr, about pwntools, the "python3-pwntools" package for python3 already exists, so it could be updated.

The only problem is that there have been changes in the Angr API and that adapt the code, someone can help?

**Comment by mpentler** [comment]
Did you have install issues too?

**Comment by Pl0414141** [comment]
Hi,

no, you can install it without problems

**Comment by mpentler** [comment]
Hmm. On Kali it shit the bed for me. I’ll see if I can get a log. Thought that’s what you meant. Never mind!

**Comment by ChrisTheCoolHut** [comment]
https://github.com/ChrisTheCoolHut/Zeratool/pull/17
